language: csharp
solution: CorrelationService.sln
before_script:
    - dotnet restore
script:
    - dotnet test Core.Tests -c Release
    - dotnet test ApiService.Tests -c Release
    - dotnet build -c Release -f netcoreapp2.0