language: csharp
solution: CorrelationService.sln
sudo: required
dist: trusty
mono: none
dotnet: 2.0.0
before_script:
    - dotnet restore
script:
    - dotnet test Core.Tests -c Release
    - dotnet test ApiService.Tests -c Release
    - dotnet build -c Release -f netcoreapp2.0