image:
    - Visual Studio 2017

before_build:
    - nuget restore
    - dotnet restore

build:
    project: CorrelationService.sln
    verbosity: minimal
    publish_aspnet_core: true

test_script:
    - dotnet test Core.Tests -c Release
    - dotnet test ApiService.Tests -c Release